import Link from "next/link";
import { fetchFeed, fetchRepoStats } from "@/lib/github";
import { getDispatch, getEnv } from "@/lib/kv";
import { getFacts } from "@/lib/facts";
import { Ticker } from "@/components/ticker";
import { StatGrid } from "@/components/stat-grid";
import { Seal } from "@/components/seal";
import type { CuratedDispatch, FeedItem, RepoStats } from "@/lib/types";

export const revalidate = 1800;

const FALLBACK_STATS: RepoStats = {
  stars: 0,
  forks: 0,
  openIssues: 0,
  openPulls: 0,
  contributors: 141,
  fetchedAt: new Date().toISOString(),
};

import { RELEASE_CONTRIBUTORS, RELEASE_HELPERS } from "@/lib/release-credits";

const FALLBACK_DISPATCH_EN: CuratedDispatch = {
  generatedAt: new Date().toISOString(),
  headline: "Quiet release week — install paths and contributor guides up to date.",
  summary:
    "This dispatch is regenerated by DeepSeek V4-Flash on a six-hour cron. Until the cron fills in fresh repo activity, the static links below are the best starting points.",
  highlights: [
    { title: "Install", href: "/en/install", tag: "shipped", blurb: "npm, Cargo, Homebrew, or a direct download." },
    { title: "Open issues", href: "https://github.com/Hmbown/CodeWhale/issues", tag: "opened", blurb: "Start with anything labelled good first issue." },
    { title: "Roadmap", href: "/en/roadmap", tag: "discussion", blurb: "What is confirmed, what is being weighed, what is ruled out." },
  ],
  movers: [],
};

const FALLBACK_DISPATCH_ZH: CuratedDispatch = {
  generatedAt: new Date().toISOString(),
  headline: "本周发布平稳——安装路径和贡献指南已同步。",
  summary:
    "本「今日要闻」由 DeepSeek V4-Flash 每六小时重新生成。在 cron 写入真实仓库动态之前，下面的固定链接是最实用的入口。",
  highlights: [
    { title: "安装", href: "/zh/install", tag: "shipped", blurb: "npm、Cargo、Homebrew，或直接下载。" },
    { title: "开放议题", href: "https://github.com/Hmbown/CodeWhale/issues", tag: "opened", blurb: "从 good first issue 标签开始。" },
    { title: "路线图", href: "/zh/roadmap", tag: "discussion", blurb: "已确认、审议中、以及已排除的功能。" },
  ],
  movers: [],
};

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isZh = locale === "zh";
  const env = await getEnv();
  const facts = await getFacts();

  let stats: RepoStats = FALLBACK_STATS;
  let feed: FeedItem[] = [];
  let dispatch: CuratedDispatch = isZh ? FALLBACK_DISPATCH_ZH : FALLBACK_DISPATCH_EN;

  try {
    [stats, feed] = await Promise.all([
      fetchRepoStats(env.GITHUB_TOKEN),
      fetchFeed(env.GITHUB_TOKEN, 12),
    ]);
  } catch (e) {
    console.error("github fetch failed", e);
  }

  try {
    const cached = await getDispatch();
    if (cached) dispatch = cached;
  } catch {
    /* keep fallback */
  }

  const highlights = isZh && dispatch.highlightsZh ? dispatch.highlightsZh : dispatch.highlights;

  return (
    <>
      <Ticker items={feed} />

      {/* HERO — what it is, plainly */}
      <section className="relative">
        <div className="mx-auto max-w-[1400px] px-4 sm:px-6 pt-10 sm:pt-14 pb-12 grid lg:grid-cols-12 gap-10">
          <div className="lg:col-span-7">
            <div className="mb-6">
              <span className="pill pill-hot">{isZh ? "开源 · 多模型 · 本地运行" : "Open source · multi-model · runs locally"}</span>
            </div>

            <h1 className="font-display tracking-crisp">
              {isZh
                ? "把最好的模型，带给尽可能多的人。"
                : "The best available models, for as many people as possible."}
            </h1>

            <p className="mt-6 text-lg text-ink-soft leading-relaxed max-w-2xl">
              <span className="font-cjk text-indigo font-semibold">CodeWhale</span>
              {isZh
                ? " 是一个开源的终端编程智能体（TUI + CLI）。你指向一个模型和一个项目，它就开始干活：读代码、改文件、跑命令、查结果、规划多步任务，并在出错时自我修正。它真正具备 agentic 能力——系统提示就是为此设计的，带计划的长时间任务是常态。目标很朴素：让本地终端工作流持续跟上编码智能体的研究和实用能力。"
                : " is an open source terminal coding agent — a TUI and a CLI. Point it at a model and a project and it gets to work: reading code, making edits, running commands, checking results, planning multi-step tasks, and correcting itself when something fails. It's genuinely agentic — the system prompt is built for it, and long-running tasks with a real plan are the norm. The goal is simple: keep the local terminal workflow current with practical coding-agent research and capabilities."}
            </p>

            {/* HONEST STATUS — what's working right now, and what isn't */}
            <div className="mt-6 px-4 py-3 hairline-t hairline-b hairline-l hairline-r text-sm leading-relaxed max-w-2xl space-y-1.5">
              <div className="eyebrow mb-1.5">{isZh ? "当前状态" : "Where things stand"}</div>
              {isZh ? (
                <>
                  <div><span className="text-jade font-mono text-xs mr-2">✓</span>当前推荐：<span className="font-mono">GLM 5.2</span>，<span className="font-mono">high</span> reasoning，在 CodeWhale 里表现很好。</div>
                  <div><span className="text-jade font-mono text-xs mr-2">✓</span>OpenAI Codex 登录可用。</div>
                  <div><span className="text-ink-mute font-mono text-xs mr-2">✗</span>Kimi OAuth 暂时不可用，正在修。</div>
                  <div className="pt-1 text-xs text-ink-mute">没看到你想要的模型或端点？<a href="https://github.com/Hmbown/CodeWhale/issues/new" className="text-indigo hover:underline">开个 issue</a>。</div>
                </>
              ) : (
                <>
                  <div><span className="text-jade font-mono text-xs mr-2">✓</span>Recommended right now: <span className="font-mono">GLM 5.2</span> on <span className="font-mono">high</span> reasoning — working very well in CodeWhale.</div>
                  <div><span className="text-jade font-mono text-xs mr-2">✓</span>OpenAI Codex login is working.</div>
                  <div><span className="text-ink-mute font-mono text-xs mr-2">✗</span>Kimi OAuth is temporarily broken; on the list.</div>
                  <div className="pt-1 text-xs text-ink-mute">Don&apos;t see a model or endpoint you want? <a href="https://github.com/Hmbown/CodeWhale/issues/new" className="text-indigo hover:underline">Open an issue</a>.</div>
                </>
              )}
            </div>

            <div className="mt-6 flex flex-wrap items-stretch sm:items-center gap-3">
              <Link
                href={isZh ? "/zh/install" : "/install"}
                className="flex-1 sm:flex-none text-center px-5 py-3 bg-ink text-paper font-mono text-sm uppercase tracking-wider hover:bg-indigo transition-colors"
              >
                {isZh ? "安装 →" : "Install →"}
              </Link>
              <Link
                href={isZh ? "/zh/docs" : "/docs"}
                className="flex-1 sm:flex-none text-center px-5 py-3 hairline-t hairline-b hairline-l hairline-r font-mono text-sm uppercase tracking-wider hover:bg-paper-deep transition-colors"
              >
                {isZh ? "文档 →" : "Docs →"}
              </Link>
              <Link
                href="https://github.com/Hmbown/CodeWhale"
                className="px-5 py-3 font-mono text-sm uppercase tracking-wider text-ink-mute hover:text-indigo transition-colors"
              >
                ★ GitHub
              </Link>
            </div>

            <div className="mt-6 flex items-center gap-4 text-xs font-mono text-ink-mute flex-wrap">
              <span>{isZh ? "由 Hmbown 维护" : "Maintained by Hmbown"}</span>
              <span className="hidden sm:inline">·</span>
              <span>{facts.version ?? "v0.8.x"}</span>
              <span className="hidden sm:inline">·</span>
              <span>{facts.providers.length} {isZh ? "个提供商" : "providers"}</span>
            </div>
          </div>

          <div className="lg:col-span-5">
            <div className="hairline-t hairline-b hairline-l hairline-r bg-paper p-5 relative">
              <div className="absolute -top-3 left-4 bg-paper px-2 eyebrow">
                {isZh ? "一行安装" : "one-line install"}
              </div>
              <pre className="code-block mt-2">
                {isZh ? (
                  <>
                    <span className="comment"># npm（推荐，无需 Rust 工具链）</span>{"\n"}
                    <span className="prompt">$</span> npm install -g codewhale{"\n"}
                    <span className="prompt">$</span> codewhale{"\n"}
                    <br />
                    <span className="comment"># 其他方式（Cargo / Homebrew / 直接下载 / 国内镜像）：</span>{"\n"}
                    <span className="comment"># <span className="key">/install</span></span>
                  </>
                ) : (
                  <>
                    <span className="comment"># npm — no Rust toolchain required</span>{"\n"}
                    <span className="prompt">$</span> npm install -g codewhale{"\n"}
                    <span className="prompt">$</span> codewhale{"\n"}
                    <br />
                    <span className="comment"># other ways (Cargo / Homebrew / direct download / China mirrors):</span>{"\n"}
                    <span className="comment"># <span className="key">/install</span></span>
                  </>
                )}
              </pre>
              <div className="mt-3 flex items-center justify-between text-[0.7rem] font-mono text-ink-mute">
                <span>{isZh ? "需要 Node 或 Rust 1.88+" : "needs Node or Rust 1.88+"}</span>
                <Link href={isZh ? "/zh/install" : "/install"} className="text-indigo hover:underline">{isZh ? "其他方式 →" : "other ways →"}</Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <StatGrid stats={stats} />

      {/* GET STARTED — the two or three steps, with the real links */}
      <section className="mx-auto max-w-[1400px] px-6 py-14">
        <div className="flex items-baseline gap-4 mb-2 hairline-b pb-4">
          <Seal char="起" />
          <h2 className="font-display">
            {isZh ? "怎么开始" : "Get started"}
          </h2>
        </div>
        <p className={`mb-8 text-ink-soft max-w-2xl ${isZh ? "leading-[1.9] tracking-wide" : "text-sm leading-relaxed"}`}>
          {isZh
            ? "三步：装好、配一个模型密钥、在项目里运行。每一步的细节都在安装指南里。"
            : "Three steps: install it, point it at a model key, and run it in a project. The install guide walks through each one."}
        </p>

        <div className="grid md:grid-cols-3 gap-0 col-rule hairline-t hairline-b">
          {(isZh
            ? [
                { n: "01", t: "安装", d: "npm 一行装好，或用 Cargo / Homebrew / 直接下载二进制。中国大陆网络有 CNB 与清华 Tuna 镜像。", cta: "安装指南 →", href: isZh ? "/zh/install" : "/install" },
                { n: "02", t: "配密钥", d: "codewhale auth set --provider deepseek（或 openrouter、anthropic、zai 等）。本地 vLLM / Ollama 无需密钥。", cta: "提供商列表 →", href: isZh ? "/zh/docs#providers" : "/docs#providers" },
                { n: "03", t: "运行", d: "在项目目录里敲 codewhale。默认 Plan 只读调查；按 Tab 切到 Agent 执行。", cta: "文档 →", href: isZh ? "/zh/docs" : "/docs" },
              ]
            : [
                { n: "01", t: "Install", d: "One npm line, or Cargo / Homebrew / a direct binary. On mainland China networks, the CNB and Tsinghua Tuna mirrors route around GitHub.", cta: "Install guide →", href: "/install" },
                { n: "02", t: "Add a key", d: "codewhale auth set --provider deepseek (or openrouter, anthropic, zai, …). A local vLLM or Ollama box needs no key at all.", cta: "Provider list →", href: "/docs#providers" },
                { n: "03", t: "Run it", d: "Type codewhale in a project. Plan mode is read-only by default; press Tab for Agent mode.", cta: "Docs →", href: "/docs" },
              ]
          ).map((item) => (
            <Link key={item.n} href={item.href} className="block p-6 hover:bg-paper-deep transition-colors">
              <div className="font-mono uppercase tracking-widest mb-2 text-[0.7rem] text-indigo">{item.n}</div>
              <h3 className="font-display text-xl mb-2">{item.t}</h3>
              <p className={`text-sm text-ink-soft mb-4 ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
                {item.d}
              </p>
              <span className="font-mono text-[0.7rem] uppercase tracking-widest text-indigo">{item.cta}</span>
            </Link>
          ))}
        </div>
      </section>

      {/* WHAT'S GOING ON — activity + dispatch */}
      <section className="bg-paper-deep hairline-t hairline-b">
        <div className="mx-auto max-w-[1400px] px-6 py-14">
          <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
            <Seal char="动" />
            <h2 className="font-display">
              {isZh ? "最近在发生什么" : "What's going on"}
            </h2>
          </div>

          {/* Recent activity from the repo */}
          {feed.length > 0 && (
            <div className="mb-10">
              <div className="eyebrow mb-3">{isZh ? "仓库近期活动" : "Recent repo activity"}</div>
              <ul className="space-y-2">
                {feed.slice(0, 6).map((item) => (
                  <li key={`${item.url}-${item.number}`} className="flex items-baseline gap-3 text-sm">
                    <span className="font-mono text-[0.66rem] text-indigo uppercase tracking-widest w-10 shrink-0">
                      {item.kind === "pull" ? "PR" : "ISS"}
                    </span>
                    <span className="font-mono text-xs text-ink-mute tabular shrink-0">#{item.number}</span>
                    <a href={item.url} className="text-ink hover:text-indigo transition-colors">
                      {item.title.slice(0, 90)}{item.title.length > 90 ? "…" : ""}
                    </a>
                  </li>
                ))}
              </ul>
              <div className="mt-4">
                <Link href={isZh ? "/zh/feed" : "/feed"} className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
                  {isZh ? "全部活动 →" : "All activity →"}
                </Link>
              </div>
            </div>
          )}

          {/* Today's dispatch */}
          <article className="grid lg:grid-cols-12 gap-x-10 gap-y-6 max-w-[1100px]">
            <h3 className="lg:col-span-12 font-display text-2xl sm:text-3xl leading-tight">
              {isZh && dispatch.headlineZh ? dispatch.headlineZh : dispatch.headline}
            </h3>
            <p className={`lg:col-span-7 text-ink-soft ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
              {isZh && dispatch.summaryZh ? dispatch.summaryZh : dispatch.summary}
            </p>
            <ul className="lg:col-span-5 space-y-3">
              {highlights.slice(0, 3).map((h, i) => (
                <li key={i} className="flex items-baseline gap-3">
                  <span className="font-mono text-[0.66rem] text-indigo uppercase tracking-widest w-16 shrink-0">
                    {h.tag}
                  </span>
                  <div>
                    <Link href={h.href} className="body-link font-display text-base leading-snug">
                      {h.title}
                    </Link>
                    <p className={`text-sm text-ink-soft mt-0.5 ${isZh ? "leading-[1.8]" : ""}`}>{h.blurb}</p>
                  </div>
                </li>
              ))}
            </ul>
          </article>
        </div>
      </section>

      {/* GET HELP — where to look, especially for China network visitors */}
      <section className="mx-auto max-w-[1400px] px-6 py-14">
        <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
          <Seal char="助" />
          <h2 className="font-display">
            {isZh ? "需要帮助？" : "Need help?"}
          </h2>
        </div>

        <div className="grid md:grid-cols-3 gap-0 col-rule hairline-t hairline-b">
          {(isZh
            ? [
                { t: "安装与配置", d: "每种安装方式、密钥设置、沙箱、CNB / 清华 Tuna 国内镜像、常见报错排查。", cta: "安装指南 →", href: "/zh/install" },
                { t: "常见问题", d: "模型、提供商、模式、MCP、技能、配置文件位置等高频问题。", cta: "FAQ →", href: "/zh/faq" },
                { t: "提议题或 PR", d: "遇到 bug 或有想法，直接在 GitHub 开 issue 或 pull request。维护者会亲自看。", cta: "参与贡献 →", href: "/zh/contribute" },
              ]
            : [
                { t: "Install & configure", d: "Every install path, key setup, sandboxing, the CNB / Tsinghua Tuna mirrors for mainland China, and troubleshooting.", cta: "Install guide →", href: "/install" },
                { t: "FAQ", d: "High-frequency questions on models, providers, modes, MCP, skills, and where config lives.", cta: "FAQ →", href: "/faq" },
                { t: "File an issue or PR", d: "Hit a bug or have an idea? Open an issue or pull request on GitHub — the maintainer reads everything personally.", cta: "Contribute →", href: "/contribute" },
              ]
          ).map((item) => (
            <Link key={item.t} href={item.href} className="block p-6 hover:bg-paper-deep transition-colors">
              <h3 className="font-display text-xl mb-2">{item.t}</h3>
              <p className={`text-sm text-ink-soft mb-4 ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
                {item.d}
              </p>
              <span className="font-mono text-[0.7rem] uppercase tracking-widest text-indigo">{item.cta}</span>
            </Link>
          ))}
        </div>

        {/* Mirror strip — surfaced up where a stuck visitor will see it, not buried in the footer */}
        {isZh && (
          <div className="mt-8 hairline-t pt-6 flex flex-wrap items-baseline gap-x-6 gap-y-3">
            <div className="eyebrow shrink-0">{isZh ? "国内镜像 / China mirrors" : "China mirrors"}</div>
            <div className="flex flex-wrap gap-4 text-sm">
              <a href="https://cnb.cool/codewhale.net/codewhale" className="text-indigo hover:underline" target="_blank" rel="noopener">CNB 镜像</a>
              <a href="https://npmmirror.com/package/codewhale" className="text-indigo hover:underline" target="_blank" rel="noopener">npmmirror</a>
              <a href="https://mirrors.tuna.tsinghua.edu.cn/help/crates.io-index.html" className="text-indigo hover:underline" target="_blank" rel="noopener">清华 Tuna crates.io</a>
            </div>
            <p className="w-full text-xs text-ink-mute leading-relaxed max-w-2xl">
              {isZh
                ? "npm 安装时可设 CODEWHALE_USE_CNB_MIRROR=1，wrapper 会改从 CNB 下载二进制。DeepSeek API（api.deepseek.com）国内直连，无需代理。"
                : "Set CODEWHALE_USE_CNB_MIRROR=1 during npm install to fetch binaries from CNB. The DeepSeek API (api.deepseek.com) is reachable from mainland China without a proxy."}
            </p>
          </div>
        )}
      </section>

      {/* RELEASE CREDITS — the community that built this release */}
      <section id="release-credits" className="mx-auto max-w-[1400px] px-6 py-14">
        <div className="flex items-baseline gap-4 mb-5 hairline-b pb-4">
          <Seal char="谢" />
          <div>
            <div className="eyebrow mb-2">{isZh ? `v${facts.version} 致谢` : `v${facts.version} credits`}</div>
            <h2 className="font-display text-3xl">
              {isZh ? "每个补丁和报告都算数" : "Every patch and report counts"}
            </h2>
          </div>
        </div>
        <div className="grid lg:grid-cols-12 gap-10">
          <div className="lg:col-span-5">
            <p className={`text-ink-soft ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
              {isZh
                ? "这一版合并和吸收了来自社区的大量工作。完整条目在 CHANGELOG 中；这里保留最新发布的公开致谢入口。"
                : "This release merged and harvested a large community tranche. The full notes live in the changelog; this keeps the latest public credit surface easy to find."}
            </p>
            <div className="flex flex-wrap gap-x-5 gap-y-2 mt-4">
              <Link href="https://github.com/Hmbown/CodeWhale/blob/main/docs/CONTRIBUTORS.md" className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
                {isZh ? "完整贡献者名单 →" : "Full contributor list →"}
              </Link>
              <Link href="https://github.com/Hmbown/CodeWhale/blob/main/CHANGELOG.md" className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
                {isZh ? "CHANGELOG →" : "CHANGELOG →"}
              </Link>
              <Link href={isZh ? "/zh/contribute" : "/contribute"} className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
                {isZh ? "参与贡献 →" : "Contribute →"}
              </Link>
              <Link href="https://github.com/Hmbown/CodeWhale/issues" className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
                {isZh ? "开放议题 →" : "Open issues →"}
              </Link>
            </div>
          </div>
          <div className="lg:col-span-7 grid gap-6">
            <div>
              <div className="eyebrow mb-3">{isZh ? "已合并 / 已吸收贡献" : "Merged and harvested contributions"}</div>
              <div className="flex flex-wrap gap-2">
                {RELEASE_CONTRIBUTORS.map((handle) => (
                  <Link
                    key={handle}
                    href={`https://github.com/${handle.slice(1)}`}
                    className="font-mono text-xs px-2 py-1 hairline-t hairline-b hairline-l hairline-r text-ink-soft hover:text-indigo hover:bg-paper-deep"
                  >
                    {handle}
                  </Link>
                ))}
              </div>
            </div>
            <div>
              <div className="eyebrow mb-3">{isZh ? "报告、复现和验证" : "Reports, repros, and verification"}</div>
              <div className="flex flex-wrap gap-2">
                {RELEASE_HELPERS.map((handle) => (
                  <Link
                    key={handle}
                    href={`https://github.com/${handle.slice(1)}`}
                    className="font-mono text-xs px-2 py-1 hairline-t hairline-b hairline-l hairline-r text-ink-soft hover:text-indigo hover:bg-paper-deep"
                  >
                    {handle}
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* JOIN IN — the project is the point */}
      <section className="bg-ink text-paper">
        <div className="mx-auto max-w-[1400px] px-6 py-20 grid lg:grid-cols-12 gap-10 items-center">
          <div className="lg:col-span-8">
            <div className="eyebrow text-paper-deep/70 mb-3">{isZh ? "这个项目" : "The project"}</div>
            <h2 className="font-display text-paper text-4xl leading-tight">
              {isZh ? "来自世界各地的开发者，把 CodeWhale 变成了今天的样子。" : "Developers from all over have made CodeWhale what it is."}
            </h2>
            <p className={`mt-5 text-paper-deep/80 max-w-2xl ${isZh ? "leading-[1.9]" : "leading-relaxed"}`}>
              {isZh
                ? "CodeWhale 起于一个人的 DeepSeek 业余项目，来自许多国家的贡献者把它塑造成了现在的样子——每一版发布上的贡献者名单就是证据。这里没有 CLA，没有赞助商优先通道，议题公开分类，版本从 main 分支发布。"
                : "CodeWhale started as one person's DeepSeek side project, and contributors from many countries have shaped it into what it is — the contributor list on every release is the proof. No CLA, no sponsor lockouts, issues triaged in the open, releases cut from main."}
            </p>
            <blockquote className={`mt-6 pl-4 border-l-2 border-indigo text-paper-deep/90 max-w-2xl ${isZh ? "leading-[1.9]" : "leading-relaxed"}`}>
              {isZh
                ? "「所有反馈都是礼物。」——这是我教书时很早就学到的一句话，也是我维护 CodeWhale 的方式。每一个 issue、PR、bug 报告或想法，都是我理解真实使用场景、做出更好决策的方式。"
                : "“All feedback is a gift.” Something I learned early in teaching, and the way I maintain CodeWhale. Every issue, PR, bug report, or idea is how I understand real use cases and make better decisions."}
            </blockquote>
            <p className={`mt-4 text-paper-deep/70 max-w-2xl text-sm ${isZh ? "leading-[1.9]" : "leading-relaxed"}`}>
              {isZh
                ? "如果你遇到用不了的地方，或者想要一个没列出来的模型——那是你能告诉这个项目的最有用的事。"
                : "If you hit something that doesn't work, or want a model that isn't listed — that's the most useful thing you can tell the project."}
            </p>
            <div className="mt-6 flex flex-wrap items-center gap-3">
              <Link
                href="https://github.com/Hmbown/CodeWhale"
                className="px-4 py-2 hairline-t hairline-b hairline-l hairline-r border-white/20 text-paper font-mono text-sm hover:bg-white/10 transition-colors"
              >
                ★ {isZh ? "在 GitHub 上 Star" : "Star on GitHub"}
              </Link>
              <Link
                href="https://github.com/Hmbown/CodeWhale/issues/new"
                className="px-4 py-2 bg-indigo text-paper font-mono text-sm hover:bg-indigo-deep transition-colors"
              >
                {isZh ? "开个 issue →" : "Open an issue →"}
              </Link>
              <Link
                href={isZh ? "/zh/contribute" : "/contribute"}
                className="px-4 py-2 font-mono text-sm text-paper-deep/80 hover:text-paper transition-colors"
              >
                {isZh ? "参与贡献 →" : "Contribute →"}
              </Link>
            </div>
          </div>

          <div className="lg:col-span-4 font-mono text-sm text-paper-deep/80 space-y-2">
            <div className="flex justify-between hairline-b border-white/15 pb-2">
              <span className="uppercase tracking-widest text-[0.66rem] text-paper-deep/60">{isZh ? "版本" : "version"}</span>
              <span className="tabular text-paper">{facts.version ?? "v0.8.x"}</span>
            </div>
            <div className="flex justify-between hairline-b border-white/15 pb-2">
              <span className="uppercase tracking-widest text-[0.66rem] text-paper-deep/60">{isZh ? "提供商" : "providers"}</span>
              <span className="tabular text-paper">{facts.providers.length}</span>
            </div>
            <div className="flex justify-between hairline-b border-white/15 pb-2">
              <span className="uppercase tracking-widest text-[0.66rem] text-paper-deep/60">{isZh ? "许可证" : "license"}</span>
              <span className="text-paper">{facts.license ?? "MIT"}</span>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
